# Generated by Django 5.1.5 on 2025-01-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
