# Generated by Django 5.1.6 on 2025-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
