# Generated by Django 5.1.6 on 2025-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
