# Generated by Django 5.1.6 on 2025-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_created_at_fooditem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
